apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
spec:
  selector:
    app: gateway
  type: NodePort
  ports:
    - name: port-service-gateway
      port: 81
      targetPort: 5001
      nodePort: 32000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deploy
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway-app
          image: rosazuccara/microservice-gateway:deploy-v1
          ports:
            - name: flask-port
              containerPort: 5001
          volumeMounts:
            - name: vol-config-gateway
              mountPath: /Gateway/config_gateway.cfg
              subPath: config_gateway.cfg
          env:
          - name: FLASK_ENV
            valueFrom:
              configMapKeyRef:
                name: configmap-gateway
                key: flaskenv
      volumes:
        - name: vol-config-gateway
          configMap:
            name: configmap-gateway