apiVersion: v1
kind: Service
metadata:
  name: servicebucket-svc
spec:
  selector:
    app: servicebucket
  type: ClusterIP
  ports:
    - name: port-service-services3
      port: 82
      targetPort: 5002
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicebucket-deploy
  labels:
    app: servicebucket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicebucket
  template:
    metadata:
      labels:
        app: servicebucket
    spec:
      containers:
        - name: servicebucket-app
          image: rosazuccara/microservice-services3:deploy-v1
          ports:
            - containerPort: 5002
          volumeMounts:
            - name: vol-config-services3
              mountPath: /ServiceS3/config_serviceS3.cfg
              subPath: config_serviceS3.cfg
          env:
          - name: FLASK_ENV
            valueFrom:
              configMapKeyRef:
                name: configmap-services3
                key: flaskenv
          - name: AWS_CLI_AUTO_PROMPT
            valueFrom:
              configMapKeyRef:
                name: configmap-aws-config
                key: aws_cli
          - name: AWS_DEFAULT_REGION
            valueFrom:
              configMapKeyRef:
                name: configmap-aws-config
                key: aws_region 
          - name: AWS_DEFAULT_OUTPUT
            valueFrom:
              configMapKeyRef:
                name: configmap-aws-config
                key: aws_output 
          envFrom:
            - secretRef:
                name: aws-credential
      volumes:
        - name: vol-config-services3
          configMap:
            name: configmap-services3



